import random

from pydantic import BaseModel

goods_list = [
    "Automobiles",
    "Car parts",
    "Motorcycles",
    "Bicycles",
    "Trucks",
    "Industrial machinery",
    "Construction equipment",
    "Medical equipment",
    "Pharmaceuticals",
    "Vaccines",
    "Diagnostic kits",
    "Hospital furniture",
    "Fresh fruits",
    "Apples",
    "Bananas",
    "Oranges",
    "Grapes",
    "Berries",
    "Citrus fruits",
    "Fresh vegetables",
    "Tomatoes",
    "Potatoes",
    "Onions",
    "Carrots",
    "Lettuce",
    "Peppers",
    "Frozen foods",
    "Frozen meat",
    "Frozen fish",
    "Frozen vegetables",
    "Frozen ready meals",
    "Dairy products",
    "Cheese",
    "Milk",
    "Butter",
    "Yogurt",
    "Meat products",
    "Beef",
    "Pork",
    "Chicken",
    "Lamb",
    "Seafood",
    "Salmon",
    "Cod",
    "Tuna",
    "Shellfish",
    "Bakery products",
    "Bread",
    "Pastries",
    "Biscuits",
    "Cakes",
    "Chocolate",
    "Confectionery",
    "Coffee",
    "Tea",
    "Soft drinks",
    "Alcoholic beverages",
    "Wine",
    "Beer",
    "Spirits",
    "Grains",
    "Wheat",
    "Corn",
    "Rice",
    "Oats",
    "Animal feed",
    "Pet food",
    "Livestock",
    "Electronics",
    "Laptops",
    "Smartphones",
    "Tablets",
    "Televisions",
    "Home appliances",
    "Textiles",
    "Clothing",
    "Shoes",
    "Bedding",
    "Curtains",
    "Furniture",
    "Wood products",
    "Paper",
    "Packaging materials",
    "Plastic products",
    "Rubber products",
    "Chemicals",
    "Fertilizers",
    "Paints",
    "Cosmetics",
    "Toys",
    "Board games",
    "Sporting goods",
    "Fitness equipment",
    "Books",
    "Magazines",
    "Office supplies",
    "Industrial raw materials",
    "Steel",
    "Aluminum",
    "Copper",
    "Batteries",
    "Solar panels",
    "Wind turbine parts",
    "Glass products",
    "Cement",
    "Ceramics",
    "Tiles",
    "Adhesives",
    "Detergents",
    "Cleaning products",
    "Medical supplies",
    "Personal protective equipment (PPE)",
    "Toiletries",
    "Flowers",
    "Plants",
    "Seeds",
    "Fabrics",
]


class Goods(BaseModel):
    """A class for goods."""

    name: str
    quantity: int
    weight: float
    volume: float
    description: str

    @classmethod
    def random(cls) -> "Goods":
        """Generate a random good with reasonable default values."""
        name = random.choice(goods_list)
        return cls(
            name=name,
            quantity=random.randint(1, 100),
            weight=random.randint(350, 1000),
            volume=random.randint(10, 1000),
            description=f"A shipment of {name.lower()}",
        )
